<a href="https://colab.research.google.com/github/royn5618/Medium_Blog_Codes/blob/master/Sparsity_and_Density.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Generating a Sparse Matrix using Count Vectorizer

In [1]:
docs = ['a demonstration of a product or technique',
        'a public meeting or march protesting against something or expressing views on a political issue',
        'record a song or piece of music to demonstrate the capabilities of a musical group or performer or as preparation for a full recording',
        'demonstrate the capabilities of software or another product']

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()

In [3]:
_cv = vectorizer.fit_transform(docs)

In [4]:
vocabulary = vectorizer.get_feature_names_out()
vocabulary

array(['against', 'another', 'as', 'capabilities', 'demonstrate',
       'demonstration', 'expressing', 'for', 'full', 'group', 'issue',
       'march', 'meeting', 'music', 'musical', 'of', 'on', 'or',
       'performer', 'piece', 'political', 'preparation', 'product',
       'protesting', 'public', 'record', 'recording', 'software',
       'something', 'song', 'technique', 'the', 'to', 'views'],
      dtype=object)

In [5]:
len(vocabulary)

34

In [6]:
_cv

<4x34 sparse matrix of type '<class 'numpy.int64'>'
	with 43 stored elements in Compressed Sparse Row format>

In [7]:
print(_cv.toarray())

[[0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0]
 [1 0 0 0 0 0 1 0 0 0 1 1 1 0 0 0 1 2 0 0 1 0 0 1 1 0 0 0 1 0 0 0 0 1]
 [0 0 1 1 1 0 0 1 1 1 0 0 0 1 1 2 0 3 1 1 0 1 0 0 0 1 1 0 0 1 0 1 1 0]
 [0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0]]


In [8]:
import numpy as np

num_elements = 34 * 4 #_cv.toarray().size
num_zeros = num_elements - np.count_nonzero(_cv.toarray())

In [9]:
num_zeros

93

In [10]:
num_zeros / num_elements

0.6838235294117647

# Generating a Dense Matrix Using Word2Vec

In [16]:
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize
from gensim.models import word2vec

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


In [11]:
vector_size = 10

In [18]:
tokenized_docs = [word_tokenize(each_train_text) for each_train_text in docs]
print(tokenized_docs)

[['a', 'demonstration', 'of', 'a', 'product', 'or', 'technique'], ['a', 'public', 'meeting', 'or', 'march', 'protesting', 'against', 'something', 'or', 'expressing', 'views', 'on', 'a', 'political', 'issue'], ['record', 'a', 'song', 'or', 'piece', 'of', 'music', 'to', 'demonstrate', 'the', 'capabilities', 'of', 'a', 'musical', 'group', 'or', 'performer', 'or', 'as', 'preparation', 'for', 'a', 'full', 'recording'], ['demonstrate', 'the', 'capabilities', 'of', 'software', 'or', 'another', 'product']]


In [22]:
w2v_model = word2vec.Word2Vec(
    tokenized_docs,
    size=vector_size,  # Dimensionality of the word vectors
    window=2,
    min_count=1,
    sg=1  # 1 for skip-gram; otherwise CBOW
)
w2v_model