<a href="https://colab.research.google.com/github/royn5618/Medium_Blog_Codes/blob/master/Sparsity_and_Density.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
docs = ['a demonstration of a product or technique',
        'a public meeting or march protesting against something or expressing views on a political issue',
        'record a song or piece of music to demonstrate the capabilities of a musical group or performer or as preparation for a full recording',
        'demonstrate the capabilities of software or another product']

In [29]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()

In [30]:
_cv = vectorizer.fit_transform(docs)

In [31]:
vocabulary = vectorizer.get_feature_names_out()
vocabulary

array(['against', 'another', 'as', 'capabilities', 'demonstrate',
       'demonstration', 'expressing', 'for', 'full', 'group', 'issue',
       'march', 'meeting', 'music', 'musical', 'of', 'on', 'or',
       'performer', 'piece', 'political', 'preparation', 'product',
       'protesting', 'public', 'record', 'recording', 'software',
       'something', 'song', 'technique', 'the', 'to', 'views'],
      dtype=object)

In [32]:
len(vocabulary)

34

In [33]:
_cv

<4x34 sparse matrix of type '<class 'numpy.int64'>'
	with 43 stored elements in Compressed Sparse Row format>

In [34]:
print(_cv.toarray())

[[0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0]
 [1 0 0 0 0 0 1 0 0 0 1 1 1 0 0 0 1 2 0 0 1 0 0 1 1 0 0 0 1 0 0 0 0 1]
 [0 0 1 1 1 0 0 1 1 1 0 0 0 1 1 2 0 3 1 1 0 1 0 0 0 1 1 0 0 1 0 1 1 0]
 [0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0]]


In [42]:
import numpy as np

num_elements = 34 * 4 #_cv.toarray().size
num_zeros = num_elements - np.count_nonzero(_cv.toarray())

In [44]:
num_zeros

93

In [43]:
num_zeros / num_elements

0.6838235294117647